### ISSUE TITLE
A user signs up in the app

### ISSUE THREAD

**Issue by sjawhar** [sjawhar/enchanted-brain#19]
## Expected Behavior
A user should be able to create a new account using an email and password. On account creation, we need to ask for
* Age
* Sex
* Ability to perceive colors: "To what extent, if any, do you have difficulty in telling colors apart that other people are easily able to tell apart":
    * 0 = "No Difficulty at all"
    * 1 = "Slight or Infrequent Difficulty" 
    * 2 = "Moderate Difficulty"
    * 3 = "Definite or Frequent Difficulty"

## Possible Solution
Pretty sure Amplify has pre-built screens for sign-up, sign-in, forgot password, etc.

## Tasks
- [x] Terms with scroll
- [x] Button back to sign-in
- [x] Scroll screen on keyboard
- [x] User exists modal

**Comment by cooperwalter** [comment]
To clarify, does "On account creation, we need to ask for" mean we want to show the input for age, sex, ability to perceive color in a new screen after the user has created an account?

**Comment by sjawhar** [comment]
I'm pretty sure the call to create a new account will fail if those attributes aren't provided. So it's not after, it's during.
