### ISSUE TITLE
A user is prompted for color choices

### ISSUE THREAD

**Issue by sjawhar** [sjawhar/enchanted-brain#23]
## Expected Behavior
During `STAGE_CHOICE_SYNESTHESIA`, the app should prompt the user for color choices:

```js
{
  stageId: 'STAGE_CHOICE_SYNESTHESIA',
  startTime: String,
  endTime: String,
  frequency: Number,
  timeout: Number,
  ... // Other attributes that aren't important right now
}
```

This stage indicates the start of a song (`startTime`). During the song, the user should prompted for a choice every `frequency` seconds until the end of the song (`endTime`). If the user doesn't make a choice within `timeout` seconds after being prompted, the prompt should disappear. The first prompt should be at `startTime + frequency`.

### Reporting a choice
To report a user's choice, send the CHOICE_MADE event:
```js
{
  event: 'CHOICE_MADE',
  data: {
    choiceType: 'CHOICE_COLOR',
    choice: String,
    timestamp: String,
  },
}
```

When sending the CHOICE_MADE event, the `timestamp` property should correspond to the time of the **prompt**, not the time of the response. For example, if `startTime` is `2019-06-26T19:15:03.000Z` and `frequency` is 20, the fourth response (at 4 x 20 = 80 seconds) would have a `timestamp` of `2019-06-26T19:16:23.000Z`, even if the user actually made the response at 82 seconds.

## Tasks
- [ ] Show the UI
- [ ] On select, hide the UI and show again later
- [ ] Send websocket message
